#!/bin/bash	
file="./Nrun" #the file where you keep your string name
Nrun=$(cat "$file")        #the output of 'cat $file' is assigned to the $name variable
for i in $(seq 1 $Nrun)
do
	echo "=================="
	echo $i
	echo "=================="
	mpirun -np 4 lmp -in 1rc
	./clc
	cat va.dat >> cva.dat
done
